"""The context-stability measurement.

For every (address specification, channel) pair we place one carrier at every
accepted anchor, damage the document, and classify each carrier's fate:

  LOST          the carrier is gone.  Safe: it is an erasure.
  NO_ANCHOR     the carrier survived but the predicate no longer fires at its
                position, so the decoder discards it.  Also safe, also an
                erasure, and free.
  MISADDRESSED  the carrier survived, the predicate fires, but the canonical
                context differs from the one used at embedding.  The decoder
                derives the *wrong* coefficient vector.  This is the only
                dangerous outcome and it is the one that has no analogue in
                generation-time watermarking.
  EXACT         survived, fires, context identical.  Usable.

Three derived rates drive every decision in MODEL.md:

  sigma_block = 1 - P(LOST)                       carrier survival
  q           = P(context identical | survived)   address survival
  refire      = P(fires | survived, context changed)

``refire`` should come out near 1/D.  That is the free suppression: a
context-change rate of 1-q only turns into a misaddressing rate of about
(1-q)/D, because a mutated context has to re-satisfy the keyed anchor test to
be accepted at all.  Measuring it rather than assuming it is the point.

Per-carrier survival under independent thinning is deliberately *not* folded in
here.  The harness measures text-level damage; ``model.py`` raises survival to
the block length analytically, because the block length depends on design
parameters the harness has no opinion about.
"""

from __future__ import annotations

import random
from collections import Counter
from hashlib import blake2b
from dataclasses import dataclass, field, asdict
from typing import Dict, Iterable, List, Sequence

from .anchors import (AnchorSpec, Site, coefficient_vector, collision_stats,
                      context_entropy_bits, find_sites, gf2_rank, site_at)
from .channels import Channel, MarkedDoc, place
from .text import Doc

def stable_seed(*parts: object) -> int:
    """Process-stable RNG seed.

    ``hash()`` on a tuple containing strings is salted per interpreter
    (PYTHONHASHSEED), so the earlier ``(seed, label, name, i).__hash__()``
    produced a different value on every run and the "same" experiment was not
    reproducible across processes.  Found in external review.
    """
    h = blake2b(digest_size=8)
    for part in parts:
        h.update(repr(part).encode("utf-8"))
        h.update(b"\x00")
    return int.from_bytes(h.digest(), "big")


EXACT = "exact"
MISADDRESSED = "misaddressed"
NO_ANCHOR = "no_anchor"
LOST = "lost"
OUTCOMES = (EXACT, MISADDRESSED, NO_ANCHOR, LOST)


@dataclass
class Tally:
    placed: int = 0
    exact: int = 0
    misaddressed: int = 0
    no_anchor: int = 0
    lost: int = 0
    # context changed but carrier survived, regardless of whether it re-fired
    survived_ctx_changed: int = 0
    survived: int = 0
    # sites whose address duplicates another site's in the same document
    duplicate_addresses: int = 0
    anchors: int = 0
    tokens: int = 0
    entropy_bits: float = 0.0
    # rank of the coefficient matrix actually generated by the surviving
    # addresses.  Entropy is descriptive; rank is the quantity that decides
    # whether the payload can be solved for, and duplicate or near-duplicate
    # addresses hurt rank in ways entropy does not capture.
    rank_achieved: int = 0
    rank_ceiling: int = 0
    n_docs: int = 0

    def add(self, other: "Tally") -> None:
        for k, v in asdict(other).items():
            setattr(self, k, getattr(self, k) + v)

    # -- derived rates -----------------------------------------------------
    @property
    def sigma_block(self) -> float:
        """P(carrier survives the visible-text damage)."""
        return self.survived / self.placed if self.placed else 0.0

    @property
    def q(self) -> float:
        """P(canonical context unchanged | carrier survived)."""
        if not self.survived:
            return 0.0
        return (self.survived - self.survived_ctx_changed) / self.survived

    @property
    def refire(self) -> float:
        """P(predicate fires | survived and context changed).  Expect ~1/D."""
        if not self.survived_ctx_changed:
            return 0.0
        return self.misaddressed / self.survived_ctx_changed

    @property
    def yield_exact(self) -> float:
        """Fraction of placed carriers that are usable.  Hard-decision yield."""
        return self.exact / self.placed if self.placed else 0.0

    @property
    def misaddress_rate(self) -> float:
        """Fraction of *accepted* carriers that are misaddressed."""
        acc = self.exact + self.misaddressed
        return self.misaddressed / acc if acc else 0.0

    @property
    def p_bsc(self) -> float:
        """Effective BSC crossover for soft decoding.

        Half of ``misaddress_rate``: a misaddressed observation is a random
        linear constraint, not an inverted one, so the true payload satisfies
        it half the time.  Bounded above by 0.5.
        """
        return 0.5 * self.misaddress_rate

    @property
    def accept_rate(self) -> float:
        """Fraction of placed carriers the decoder accepts (right or wrong)."""
        acc = self.exact + self.misaddressed
        return acc / self.placed if self.placed else 0.0

    @property
    def rank_fraction(self) -> float:
        """Achieved rank as a share of the payload dimension it could reach."""
        return self.rank_achieved / self.rank_ceiling if self.rank_ceiling else 0.0

    @property
    def anchor_density(self) -> float:
        """Anchors per 100 tokens."""
        return 100.0 * self.anchors / self.tokens if self.tokens else 0.0

    @property
    def collision_rate(self) -> float:
        return self.duplicate_addresses / self.anchors if self.anchors else 0.0

    def summary(self) -> Dict[str, float]:
        return {
            "placed": self.placed,
            "sigma_block": round(self.sigma_block, 4),
            "q": round(self.q, 4),
            "refire": round(self.refire, 4),
            "yield_exact": round(self.yield_exact, 4),
            "misaddr_rate": round(self.misaddress_rate, 5),
            "p_bsc": round(self.p_bsc, 5),
            "accept_rate": round(self.accept_rate, 4),
            "anchor_density_per100": round(self.anchor_density, 3),
            "collision_rate": round(self.collision_rate, 4),
            "entropy_bits": round(self.entropy_bits / max(1, self.n_docs), 2),
            "rank_fraction": round(self.rank_fraction, 4),
        }


def measure_one(doc: Doc, key: bytes, spec: AnchorSpec, channel: Channel,
                rng: random.Random, per_site: int = 1,
                payload_bits: int = 80, sparse_degree: int = 0) -> Tally:
    """Place, damage, reclassify.  One document, one channel."""
    sites = find_sites(doc, key, spec)
    t = Tally(n_docs=1, tokens=len(doc), anchors=len(sites))
    if not sites:
        return t

    n_sites, n_distinct, wasted = collision_stats(sites)
    t.duplicate_addresses = n_sites - n_distinct
    t.entropy_bits = context_entropy_bits(sites)

    md: MarkedDoc = place(doc, [s.gap for s in sites], per_site=per_site)
    original_ctx = {}
    for site_idx, s in enumerate(sites):
        for j in range(per_site):
            original_ctx[site_idx * per_site + j] = s.context
    t.placed = len(original_ctx)

    surviving_ctx: List[tuple[bytes, int]] = []
    damaged = channel(md, rng)
    gaps = damaged.gap_of_marks()
    toks = damaged.tokens

    for mark_id, ctx0 in original_ctx.items():
        gap = gaps.get(mark_id)
        if gap is None:
            t.lost += 1
            continue
        t.survived += 1
        found: Site | None = site_at(toks, gap, key, spec)
        ctx_now = spec.ctx.context_at(toks, gap)
        changed = ctx_now != ctx0
        if changed:
            t.survived_ctx_changed += 1
        if found is None:
            t.no_anchor += 1
        elif changed:
            t.misaddressed += 1
        else:
            t.exact += 1
            surviving_ctx.append((ctx0, mark_id % per_site))

    # Rank of the coefficient matrix the surviving addresses actually generate.
    # Capped at the payload dimension; duplicate addresses contribute nothing,
    # which is precisely the failure entropy only hints at.
    vectors = [coefficient_vector(key, ctx, j, payload_bits, sparse_degree)
               for ctx, j in surviving_ctx]
    t.rank_achieved = gf2_rank(vectors)
    t.rank_ceiling = min(payload_bits, len(vectors))
    return t


def measure(docs: Sequence[Doc], key: bytes, specs: Sequence[AnchorSpec],
            channels: Dict[str, Channel], seed: int = 0,
            per_site: int = 1) -> Dict[tuple[str, str], Tally]:
    """Full sweep.  Returns {(spec_label, channel_name): Tally}."""
    out: Dict[tuple[str, str], Tally] = {}
    for spec in specs:
        for name, ch in channels.items():
            agg = Tally()
            for i, doc in enumerate(docs):
                rng = random.Random(stable_seed(seed, spec.label(), name, i))
                agg.add(measure_one(doc, key, spec, ch, rng, per_site=per_site))
            out[(spec.label(), name)] = agg
    return out


def to_rows(results: Dict[tuple[str, str], Tally]) -> List[Dict[str, object]]:
    rows = []
    for (spec, chan), t in results.items():
        row: Dict[str, object] = {"spec": spec, "channel": chan}
        row.update(t.summary())
        rows.append(row)
    return rows


def write_csv(rows: Sequence[Dict[str, object]], path: str) -> None:
    import csv
    if not rows:
        return
    keys = list(rows[0].keys())
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)
